name: Sync and Auto Merge

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: WizisCool
          base: master
          head: master
          ignore_fail: true

  automerge:
    needs: sync  # 仅在 sync 任务成功完成后运行
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.repository == github.event.repository.full_name) }}
        name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
