# This is a basic workflow to help you get started with Actions

name: build_shards_json


# Controls when the workflow will run
on:
  push:
    branches:
      - master
    paths:
      - '**.shard'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Concurrency can be used at workflow level or job leve
concurrency:
  group: group-build
  
  # If this is enabled it will cancel current running and start latest
  cancel-in-progress: true


jobs:
  generate_shards_json:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # download the parser
      - name: Download shards_json_generator.exe
        run: curl.exe -o ${{ runner.temp }}\shards_json_generator.exe -L https://github.com/badspacebar/sdk/releases/download/v1/shards_json_generator.exe

      # Runs a single command using the runners shell
      - name: Run shards_json_generator
        run: ${{ runner.temp }}\shards_json_generator.exe ${{ github.workspace }}\files\shards
        
      - name: Run shards_json_generator
        run: dir ${{ github.workspace }}\files
        
      - name: Run shards_json_generator
        run: Move-Item -force ${{ github.workspace }}\files\hanbot_shards.json ${{ github.workspace }}\files\shards.json

      # Update shards.json
      - name: Update shards.json
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
              files/shards.json
            commit-msg: Update shards.json
            github-token: ${{ secrets.GITHUB_TOKEN }}
